spring.application.name=payment-events-processor

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_events
spring.datasource.username=payment_events
spring.datasource.password=payment_events
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.open-in-view=false

# Kafka
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.properties.schema.registry.url=http://localhost:8081

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Outbox Publisher
outbox.publisher.fixed-delay-ms=5000

# Kafka Consumer
spring.kafka.consumer.group-id=payment-processor
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.specific.avro.reader=true

# Kafka Streams
spring.kafka.streams.application-id=payment-events-streams
spring.kafka.streams.bootstrap-servers=${spring.kafka.bootstrap-servers}
spring.kafka.streams.properties.schema.registry.url=${spring.kafka.properties.schema.registry.url}
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde