spring.application.name=payment-events-processor

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_events
spring.datasource.username=payment_events
spring.datasource.password=payment_events
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.open-in-view=false

# Kafka
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.properties.schema.registry.url=http://localhost:8081

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs