spring.application.name=payment-events-processor

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_events
spring.datasource.username=payment_events
spring.datasource.password=payment_events
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs